### ISSUE TITLE
stuff_train2017.json missing

### ISSUE THREAD

**Issue by ChenghaoMou** [uvavision/Text2Scene#1]
I was trying to run the composite experiment and following error occurred.

```
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/sample_composites.txt.2019-10-16_08-31-33
+ exec
++ tee -a experiments/logs/sample_composites.txt.2019-10-16_08-31-33
tee: experiments/logs/sample_composites.txt.2019-10-16_08-31-33: No such file or directory
+ echo Logging output to experiments/logs/sample_composites.txt.2019-10-16_08-31-33
Logging output to experiments/logs/sample_composites.txt.2019-10-16_08-31-33
+ ./tools/composites_demo.py --cuda --for_visualization=True --use_super_category=True --use_patch_background=True --n_shape_hidden=256 --where_attn=2 --where_attn_2d=True --pretrained=composites_final
loading annotations into memory...
Done (t=19.85s)
creating index...
index created!
Traceback (most recent call last):
  File "./tools/composites_demo.py", line 97, in <module>
    composites_demo(config)
  File "./tools/composites_demo.py", line 68, in composites_demo
    traindb = composites_coco(config, 'train', '2017')
  File "/auto/nlg-05/chengham/Text2Scene/tools/../lib/datasets/composites_coco.py", line 30, in __init__
    self.get_coco_general_info()
  File "/auto/nlg-05/chengham/Text2Scene/tools/../lib/datasets/composites_coco.py", line 79, in get_coco_general_info
    self.cocoStuffAPI = COCO(self.get_ann_file('stuff'))
  File "/auto/nlg-05/chengham/Text2Scene/tools/../lib/datasets/composites_coco.py", line 418, in get_ann_file
    assert osp.exists(ann_path), 'Path does not exist: {}'.format(ann_path)
AssertionError: Path does not exist: /auto/nlg-05/chengham/Text2Scene/tools/../lib/../data/coco/annotations/stuff_train2017.json

```
Is there a step I am missing? I used all fetch_data, fetch_model, and fetch_aux scripts.

**Comment by fwtan** [comment]
Hi, we updated the fetch_data script (https://github.com/uvavision/Text2Scene/blob/master/experiments/scripts/fetch_data.sh). You can rerun the script or download the stuff annotation directly: http://images.cocodataset.org/annotations/stuff_annotations_trainval2017.zip
