### ISSUE TITLE
error no 2

### ISSUE THREAD

**Issue by mnigam504** [uvavision/Text2Scene#8]
Traceback (most recent call last):
  File "C:\Users\asus\cocoapi\PythonAPI\Text2Scene\tools\abstract_demo.py", line 35, in <module>
    abstract_demo(config)
  File "C:\Users\asus\cocoapi\PythonAPI\Text2Scene\tools\abstract_demo.py", line 20, in abstract_demo
    input_sentences = json_load('examples/abstract_samples.json')
  File "C:\Users\asus\cocoapi\PythonAPI\Text2Scene\tools\..\lib\abstract_utils.py", line 53, in json_load
    with open(path, 'r') as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'examples/abstract_samples.json'

**Comment by fwtan** [comment]
Hi, the file is included in the github: https://github.com/uvavision/Text2Scene/blob/master/examples/abstract_samples.json, you may want to set the path properly.
